### ISSUE TITLE
Flood errors in chat

### ISSUE THREAD

**Issue by ccyounga** [RefracDevelopment/SimpleStaffChat2#13]
Greetings. After the last update, the plugin began to flood the chat with errors.

[13:31:45 ERROR]: Could not pass event AsyncPlayerChatEvent to SimpleStaffChat2 v2.5
java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null
        at java.lang.String.startsWith(String.java:2253) ~[?:?]
        at java.lang.String.startsWith(String.java:2296) ~[?:?]
        at me.refracdevelopment.simplestaffchat.spigot.listeners.ChatListener.onChat(ChatListener.java:103) ~[SimpleStaffChat2-2.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor109.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:195) ~[paper-1.18.2.jar:git-Paper-386]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:67) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2224) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2135) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2101) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket$1.run(ServerboundChatPacket.java:40) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

[13:44:12 ERROR]: Could not pass event AsyncPlayerChatEvent to SimpleStaffChat2 v2.5
java.lang.NullPointerException: null

**Comment by Refrac** [comment]
@ccyounga Admin and Dev chats were added you will need to add the necessary config changes.

**Comment by Refrac** [comment]
@ccyounga Make sure your config has all of the values inside of the default one: https://github.com/RefracDevelopment/SimpleStaffChat2/blob/master/src/main/resources/config.yml

**Comment by ccyounga** [comment]
Teach the plugin to update the config automatically.
I will certainly try myself.

**Comment by Refrac** [comment]
@ccyounga I will look into adding this in the next update(s).

**Comment by Refrac** [comment]
@ccyounga This has been released in 2.6 you can download from one of the following:
https://www.spigotmc.org/resources/91883
https://polymart.org/resource/1173
https://songoda.com/marketplace/product/645
https://www.mc-market.org/resources/22491
